### ISSUE TITLE
Error: Cannot find module '../config'

### ISSUE THREAD

**Issue by davidsierradz** [Putnam14/ReadingLength#16]
```bash
$ ~/code/ReadingLength/node_modules/.bin/nodemon bin/www
[nodemon] 1.17.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node bin/www`
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '../config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/neuromante/code/ReadingLength/routes/index.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by Putnam14** [comment]
This isn't really an issue, just a lack of my documentation. I'll get around to writing a README eventually.
For this to run, among other things, you need a config.js file in the project root. This has things like the Amazon API keys, the path to your mongo server and credentials, defaults, etc. You also need a mongo installation running preconfigured with a suitable schema. You could probably figure it all out by looking at the code which references it, but I'm planning a refactor and documentation sprint one of these weekends. Summer is hard for coding with so much to do outdoors!
